import 'dotenv/config';
import express from 'express';
import cors from 'cors';

const app = express();
const PORT = Number(process.env.PORT || 3000);
const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = process.env.OPENROUTER_MODEL || 'openrouter/free';

app.use(cors());
app.use(express.json({ limit: '1mb' }));

app.get('/health', (_req, res) => {
  res.json({ success: true, configured: Boolean(process.env.OPENROUTER_API_KEY), model: MODEL });
});

const systemPrompt = `You are WebGen AI, an expert frontend engineer and UI designer.
Generate ONE complete standalone HTML document from the user's website request.
Rules:
- Return ONLY raw HTML. Do not use Markdown fences and do not add explanations.
- Include all CSS in a <style> tag and all JavaScript in a <script> tag.
- Do not require React, npm, external CSS files, local files, or build tools.
- You may use Google Fonts via @import or a normal stylesheet link, but the page must still be usable if fonts fail.
- Make the page polished, modern, accessible and fully responsive on phones, tablets and desktops.
- Include a working mobile navigation menu, smooth scrolling, hover/focus states, buttons, forms with friendly client-side validation, and useful micro-interactions where appropriate.
- Use semantic HTML, good contrast, responsive grids/flex layouts and fluid typography.
- Never put secrets, API keys, passwords or server code in the generated website.
- Use realistic content based on the request; do not mention that it was generated by AI unless requested.
- Use inline SVG icons when icons are needed instead of depending on icon packages.
- If images are useful, use stable Unsplash source URLs or tasteful gradients/placeholders; do not reference local files.
- The result must work when saved as index.html and opened directly in a browser.`;

function cleanHtml(text) {
  let value = String(text || '').trim();
  value = value.replace(/^```(?:html)?\s*/i, '').replace(/\s*```$/i, '').trim();
  const start = value.toLowerCase().indexOf('<!doctype');
  if (start > 0) value = value.slice(start);
  const htmlStart = value.toLowerCase().indexOf('<html');
  if (start < 0 && htmlStart > 0) value = value.slice(htmlStart);
  return value.trim();
}

app.post('/api/generate', async (req, res) => {
  try {
    if (!process.env.OPENROUTER_API_KEY) {
      return res.status(500).json({ success: false, error: 'OPENROUTER_API_KEY is missing. Add it to .env and restart the server.' });
    }

    const prompt = typeof req.body?.prompt === 'string' ? req.body.prompt.trim() : '';
    if (!prompt) return res.status(400).json({ success: false, error: 'Please enter a website prompt.' });
    if (prompt.length > 12000) return res.status(400).json({ success: false, error: 'Prompt is too long. Keep it under 12,000 characters.' });

    const response = await fetch(OPENROUTER_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'http://localhost:5173',
        'X-Title': 'WebGen AI'
      },
      body: JSON.stringify({
        model: MODEL,
        temperature: 0.7,
        max_tokens: 18000,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Build this website:\n\n${prompt}` }
        ]
      })
    });

    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      const message = data?.error?.message || `OpenRouter request failed with HTTP ${response.status}`;
      return res.status(response.status).json({ success: false, error: message });
    }

    const content = data?.choices?.[0]?.message?.content;
    const html = cleanHtml(content);
    if (!html || !html.toLowerCase().includes('<html')) {
      return res.status(502).json({ success: false, error: 'The AI returned an invalid website document. Please try again.' });
    }

    res.json({ success: true, html, model: data?.model || MODEL });
  } catch (error) {
    console.error(error);
    res.status(500).json({ success: false, error: error?.message || 'Unexpected server error.' });
  }
});

app.use((_req, res) => res.status(404).json({ success: false, error: 'Route not found.' }));

app.listen(PORT, () => {
  console.log(`WebGen AI API running at http://localhost:${PORT}`);
  console.log(`OpenRouter configured: ${Boolean(process.env.OPENROUTER_API_KEY)}`);
});
