import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import JSZip from 'jszip';
import { Download, Eye, Sparkles, Copy, RefreshCw, Code2, Check, WandSparkles, ExternalLink } from 'lucide-react';
import './styles.css';

const examples = [
  'Create a premium dark purple dentist website with navbar, hero, services, doctors, testimonials, pricing and contact form.',
  'Create a modern gym website with bold typography, membership plans, trainers, classes, testimonials and a contact section.',
  'Create a luxury car dealership website with a cinematic hero, featured cars, filters, financing section and inquiry form.',
  'Create a clean school website with admissions, programs, faculty, events, testimonials and a contact section.'
];

function App() {
  const [prompt, setPrompt] = useState('');
  const [html, setHtml] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [view, setView] = useState('preview');

  const canGenerate = useMemo(() => prompt.trim().length > 0 && !loading, [prompt, loading]);

  async function generate() {
    if (!prompt.trim()) return;
    setLoading(true);
    setError('');
    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt })
      });
      const data = await response.json().catch(() => ({}));
      if (!response.ok || !data.success) throw new Error(data.error || `Server returned HTTP ${response.status}.`);
      setHtml(data.html);
      setView('preview');
    } catch (err) {
      setError(err.message || 'Generation failed.');
    } finally {
      setLoading(false);
    }
  }

  function downloadHtml() {
    if (!html) return;
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'webgen-website.html';
    a.click();
    URL.revokeObjectURL(url);
  }

  async function downloadZip() {
    if (!html) return;
    const zip = new JSZip();
    zip.file('index.html', html);
    zip.file('README.txt', 'Generated by WebGen AI. Open index.html in any modern browser.');
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'webgen-website.zip';
    a.click();
    URL.revokeObjectURL(url);
  }

  async function copyCode() {
    if (!html) return;
    await navigator.clipboard.writeText(html);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand"><div className="brand-icon"><Sparkles size={20}/></div><div><strong>WebGen AI</strong><span>AI Website Generator</span></div></div>
        <div className="status"><i/> OpenRouter AI</div>
      </header>

      <main>
        <section className="hero">
          <div className="eyebrow"><WandSparkles size={16}/> Build websites with AI</div>
          <h1>Turn your idea into a <em>real website.</em></h1>
          <p>Describe what you want and WebGen AI creates a complete responsive website with HTML, CSS and JavaScript.</p>

          <div className="generator-card">
            <div className="prompt-head"><span><Code2 size={16}/> Website prompt</span><small>Be specific for better results</small></div>
            <textarea value={prompt} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') generate(); }} placeholder="Example: Create a modern dark purple dentist website with navbar, hero section, services, doctors, testimonials and contact form..." />
            <div className="prompt-foot">
              <div className="chips">{examples.slice(0, 3).map((x, i) => <button key={i} onClick={() => setPrompt(x)}>{['Dentist','Gym','Car'][i]}</button>)}</div>
              <button className="generate" disabled={!canGenerate} onClick={generate}>{loading ? <><RefreshCw className="spin" size={17}/> Generating...</> : <><Sparkles size={17}/> Generate website</>}</button>
            </div>
          </div>
          {error && <div className="error">{error}</div>}
        </section>

        {html && <section className="workspace">
          <div className="workspace-head">
            <div><h2>Your website</h2><span>Live preview & source</span></div>
            <div className="actions">
              <button onClick={() => setView('preview')} className={view === 'preview' ? 'active' : ''}><Eye size={16}/> Preview</button>
              <button onClick={() => setView('code')} className={view === 'code' ? 'active' : ''}><Code2 size={16}/> Code</button>
              <button onClick={copyCode}>{copied ? <Check size={16}/> : <Copy size={16}/>} {copied ? 'Copied' : 'Copy'}</button>
              <button onClick={downloadHtml}><Download size={16}/> HTML</button>
              <button onClick={downloadZip} className="download"><Download size={16}/> Download ZIP</button>
            </div>
          </div>
          <div className="preview-wrap">
            {view === 'preview' ? <iframe title="Generated website preview" sandbox="allow-scripts allow-forms" srcDoc={html} /> : <pre>{html}</pre>}
          </div>
        </section>}

        {!html && <section className="examples"><div className="section-title"><span>Try an example</span><small>One click to start</small></div><div className="example-grid">{examples.map((x, i) => <button key={i} onClick={() => setPrompt(x)}><span>{['🦷','🏋️','🚘','🎓'][i]}</span><div><strong>{['Dentist clinic','Fitness gym','Car dealership','Modern school'][i]}</strong><p>{x}</p></div><ExternalLink size={16}/></button>)}</div></section>}
      </main>
      <footer>WebGen AI · Generate, preview and download responsive websites.</footer>
    </div>
  );
}

createRoot(document.getElementById('root')).render(<App />);
