const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";
const MODEL = process.env.OPENROUTER_MODEL || "openrouter/free";

const systemPrompt = `
You are WebGen AI, an expert frontend engineer and UI designer.

Generate ONE complete standalone HTML document from the user's website request.

Rules:
- Return ONLY raw HTML.
- Do not use Markdown code fences.
- Do not add explanations.
- Include all CSS inside a <style> tag.
- Include all JavaScript inside a <script> tag.
- Do not require React, npm, external CSS files, local files, or build tools.
- Make the website polished, modern, professional and fully responsive.
- It must work perfectly on mobile, tablet and desktop.
- Include a working mobile navigation menu.
- Include smooth scrolling.
- Include hover and focus states.
- Include working buttons.
- Include forms with client-side validation where appropriate.
- Use semantic HTML.
- Use good color contrast.
- Use responsive grids and flexbox.
- Use fluid typography.
- Add useful micro-interactions where appropriate.
- Never expose API keys, passwords, secrets or server-side code.
- Use realistic content based on the user's request.
- Do not mention that the website was generated by AI unless requested.
- Use inline SVG icons when icons are needed.
- If images are useful, use stable Unsplash URLs or gradients/placeholders.
- Do not reference local files.
- The final result must work when saved as index.html and opened directly in a browser.
`;

function cleanHtml(text) {
  let value = String(text || "").trim();

  // Remove Markdown code fences
  value = value
    .replace(/^```(?:html)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();

  // Find DOCTYPE or HTML start
  const doctypeIndex = value.toLowerCase().indexOf("<!doctype");
  const htmlIndex = value.toLowerCase().indexOf("<html");

  const start =
    doctypeIndex >= 0
      ? doctypeIndex
      : htmlIndex >= 0
      ? htmlIndex
      : -1;

  if (start > 0) {
    value = value.slice(start);
  }

  return value.trim();
}

function sendJson(res, status, body) {
  res.status(status).json(body);
}

export default async function handler(req, res) {
  // Handle CORS / preflight
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
    res.setHeader(
      "Access-Control-Allow-Headers",
      "Content-Type, Authorization"
    );

    return res.status(204).end();
  }

  // Only POST is allowed
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST, OPTIONS");

    return sendJson(res, 405, {
      success: false,
      error: "Method not allowed."
    });
  }

  try {
    // Check API key
    if (!process.env.OPENROUTER_API_KEY) {
      return sendJson(res, 500, {
        success: false,
        error:
          "OPENROUTER_API_KEY is missing in Vercel Environment Variables."
      });
    }

    // Get prompt
    const prompt =
      typeof req.body?.prompt === "string"
        ? req.body.prompt.trim()
        : "";

    if (!prompt) {
      return sendJson(res, 400, {
        success: false,
        error: "Please enter a website prompt."
      });
    }

    if (prompt.length > 12000) {
      return sendJson(res, 400, {
        success: false,
        error: "Prompt is too long. Keep it under 12,000 characters."
      });
    }

    // Send request to OpenRouter
    const response = await fetch(OPENROUTER_URL, {
      method: "POST",

      headers: {
        Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
        "HTTP-Referer":
          req.headers.origin ||
          req.headers.referer ||
          "https://vercel.com",
        "X-Title": "WebGen AI"
      },

      body: JSON.stringify({
        model: MODEL,

        temperature: 0.7,

        max_tokens: 18000,

        messages: [
          {
            role: "system",
            content: systemPrompt
          },
          {
            role: "user",
            content: `Build this website:\n\n${prompt}`
          }
        ]
      })
    });

    const data = await response.json().catch(() => ({}));

    // OpenRouter error
    if (!response.ok) {
      const message =
        data?.error?.message ||
        `OpenRouter request failed with HTTP ${response.status}`;

      return sendJson(res, response.status, {
        success: false,
        error: message
      });
    }

    // Get AI response
    const content = data?.choices?.[0]?.message?.content;

    const html = cleanHtml(content);

    // Validate generated HTML
    if (!html || !html.toLowerCase().includes("<html")) {
      return sendJson(res, 502, {
        success: false,
        error:
          "The AI returned an invalid website document. Please try again."
      });
    }

    // Success
    return sendJson(res, 200, {
      success: true,
      html,
      model: data?.model || MODEL
    });
  } catch (error) {
    console.error("WebGen API error:", error);

    return sendJson(res, 500, {
      success: false,
      error:
        error?.message ||
        "Unexpected server error."
    });
  }
}